/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ["class"],
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                text: {
                    primary: 'var(--text-primary)',
                    secondary: 'var(--text-secondary)',
                    muted: 'var(--text-muted)',
                    'on-primary': 'var(--text-on-primary)',
                    disabled: 'var(--text-disabled)',
                },
                surface: {
                    page: 'var(--surface-page)',
                    card: 'var(--surface-card)',
                    elevated: 'var(--surface-elevated)',
                    input: 'var(--surface-input)',
                },
                action: {
                    primary: 'var(--action-primary)',
                    'primary-hover': 'var(--action-primary-hover)',
                    'primary-pressed': 'var(--action-primary-pressed)',
                    secondary: 'var(--action-secondary)',
                    'secondary-hover': 'var(--action-secondary-hover)',
                },
                border: {
                    DEFAULT: 'var(--border-default)',
                    subtle: 'var(--border-subtle)',
                    focus: 'var(--border-focus)',
                    input: 'var(--border-input)',
                },
                status: {
                    success: 'var(--status-success)',
                    progress: 'var(--status-progress)',
                    inactive: 'var(--status-inactive)',
                    warning: 'var(--status-warning)',
                    error: 'var(--status-error)',
                },
            },
            fontSize: {
                xs: 'var(--text-xs)',
                sm: 'var(--text-sm)',
                base: 'var(--text-base)',
                lg: 'var(--text-lg)',
                xl: 'var(--text-xl)',
                '2xl': 'var(--text-2xl)',
                '3xl': 'var(--text-3xl)',
            },
            fontWeight: {
                normal: 'var(--font-normal)',
                medium: 'var(--font-medium)',
                semibold: 'var(--font-semibold)',
                bold: 'var(--font-bold)',
            },
            lineHeight: {
                tight: 'var(--leading-tight)',
                normal: 'var(--leading-normal)',
                relaxed: 'var(--leading-relaxed)',
            },
            spacing: {
                1: 'var(--space-1)',
                2: 'var(--space-2)',
                3: 'var(--space-3)',
                4: 'var(--space-4)',
                5: 'var(--space-5)',
                6: 'var(--space-6)',
                8: 'var(--space-8)',
                10: 'var(--space-10)',
                12: 'var(--space-12)',
                16: 'var(--space-16)',
            },
            borderRadius: {
                sm: 'var(--radius-sm)',
                md: 'var(--radius-md)',
                lg: 'var(--radius-lg)',
                xl: 'var(--radius-xl)',
                '2xl': 'var(--radius-2xl)',
                full: 'var(--radius-full)',
            },
            boxShadow: {
                sm: 'var(--shadow-sm)',
                md: 'var(--shadow-md)',
                lg: 'var(--shadow-lg)',
                xl: 'var(--shadow-xl)',
            },
            fontFamily: {
                sans: 'var(--font-family-primary)',
            },
            transitionDuration: {
                fast: 'var(--transition-fast)',
                base: 'var(--transition-base)',
                slow: 'var(--transition-slow)',
            },
            zIndex: {
                base: 'var(--z-base)',
                dropdown: 'var(--z-dropdown)',
                sticky: 'var(--z-sticky)',
                overlay: 'var(--z-overlay)',
                modal: 'var(--z-modal)',
                toast: 'var(--z-toast)',
                tooltip: 'var(--z-tooltip)',
            },
        },
    },
    plugins: [],
}
